Add to do list
karam084/to_do_list pull request #1
Opened 2022-02-25 03:51 UTC by karam084

-*  Project requirements

- Set up a new project with webpack that is based on the webpack exercise you have already completed.
- Create an index.html file and write your HTML markup here. Create an empty To Do List placeholder (<div> or <ul> element). The index.html file must be set as a template using the HTML Webpack Plugin.
- Create an index.js file and set an array of some simple to do tasks (array of objects). Each task object should contain three keys:
- description [string].
- completed [bool].
- index: [number].
- Write a function to iterate over the tasks array and populate an HTML list item element for each task.
- On page load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
- Create a style.css and set rules for the To Do List. CSS must be loaded by Webpack Style/CSS Loader. Your list should be a clone of the part of the minimalist project captured in the video below.

2022-02-25 19:27 UTC, medaminedev66 requested changes
Hi @karam084 , :wave:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_See the inline comments below for more required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-25 19:27 UTC, medaminedev66 commented on README.md
>  To Do List project
- [ ] Kindly add a description of your project to the Readme file so users can know about your project.

2022-02-25 19:27 UTC, medaminedev66 commented on README.md
> +[Demo](https://github.com/karam084/to_do_list)
- [ ] The demo link is leading to a wrong page. Kindly fix this.

2022-02-25 19:27 UTC, medaminedev66 commented on README.md
- [ ] The MIT license link is broken, kindly fix this. Your README is the entry point of your users and having it well written without any broken links gives a good first impression and maximizes the potential of your product to your users.

2022-02-25 19:27 UTC, medaminedev66 commented on webpack.config.js
> +};
- [ ] The webpack is not configured well. It shows this error after running `npm start`:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/77190203/155774936-4e10ccdf-efcf-46de-92a4-31eeb9d08d5b.png">


- Kindly make sure that your project opened successfully after running `npm start`

2022-02-25 19:27 UTC, medaminedev66 commented on src/index.js
> +
- [ ] Following the project requirements, your project should have an array of some simple to-do tasks (array of objects) with each object containing three keys - description [string], completed [bool], index: [number]. You can create more properties or name these properties differently. Checkout the project requirement bellow 👇 :
<img width="693" alt="image" src="https://user-images.githubusercontent.com/77190203/155723997-d526293f-e34d-45f9-a734-b941ca827130.png">


- [ ] Your project also should have a function that iterates over the tasks array and populates the HTML list item element for each task.

2022-02-25 19:27 UTC, medaminedev66 commented on README.md
> +- https://www.youtube.com/watch?v=AcUd-_Yjjqg
- [ ] These links doesn't have any relation with your project. Kindly remove them to make your project professional.

2022-02-26 00:05 UTC, mmsesay requested changes
Hi @karam084, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-26 00:05 UTC, mmsesay commented on webpack.config.js
> +};
- [x] I see you have worked on the required changes. However, it seems like the npm problem is still around. See below screenshots of the errors I encounter upon running `npm start`
Please try to check this out.

Shot 1
![a1](https://user-images.githubusercontent.com/39523312/155818696-a1b65278-d952-47bc-86e7-c7d7842e6321.png)

Shot 2
![a2](https://user-images.githubusercontent.com/39523312/155818698-ad419400-6789-4bf2-bc9d-5ae00de8ebc6.png)

2022-02-26 00:05 UTC, mmsesay commented on src/index.js
> +const createNewTaskElement = function tasks(taskString) {
- [ ] As suggested by the previous reviewer, you should create an array with to-do tasks with each object containing three keys.
See example:
```
const tasks = [
  {
    description: 'An example description in string',
    completed: false,
    index: 10,
  },
];
```

2022-02-26 14:03 UTC, medaminedev66 requested changes
Hi @karam084 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] There should be no custom changes to linter config. Kindly set up the linter again in your repository.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-27 01:51 UTC, Amrhub approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @karam084, 👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-27 02:00 UTC, merged